import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import {
  AGGREGATE_PATH,
  REGISTRY_PATH,
  checkRegistry,
  checkRegistryMembership,
  readRegistry,
  renderAggregate,
} from './assemble-registry.ts'
import { scaffoldPlugin } from './scaffold-plugin.ts'

const tempDirs: string[] = []

function fixtureRoot(): string {
  const dir = mkdtempSync(join(tmpdir(), 'dsh-plugin-registry-'))
  tempDirs.push(dir)
  return dir
}

afterEach(() => {
  for (const dir of tempDirs.splice(0)) rmSync(dir, { recursive: true, force: true })
})

function writeFile(root: string, rel: string, content = ''): void {
  const path = join(root, rel)
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content)
}

function writeRegistry(root: string, plugins: string[]): void {
  writeFile(root, REGISTRY_PATH, `${JSON.stringify({ plugins }, null, 2)}\n`)
}

function writeAggregate(root: string, content: string): void {
  writeFile(root, AGGREGATE_PATH, content)
}

describe('renderAggregate', () => {
  it('renders an empty overlay for an empty registry', () => {
    expect(renderAggregate([])).toBe([
      '# Generated by scripts/assemble-registry.ts — do not edit by hand.',
      '# Regenerate: pnpm run plugin:assemble — verify: pnpm run plugin:assemble:check',
      '[]',
      '',
    ].join('\n'))
  })

  it('renders one include entry per registered plugin in registry order', () => {
    expect(renderAggregate(['zeta', 'alpha'])).toContain('    path: ./zeta/cordis.yml')
    expect(renderAggregate(['zeta', 'alpha'])).toContain('    path: ./alpha/cordis.yml')
    expect(renderAggregate(['zeta', 'alpha']).indexOf('zeta/cordis.yml'))
      .toBeLessThan(renderAggregate(['zeta', 'alpha']).indexOf('alpha/cordis.yml'))
  })
})

describe('checkRegistry', () => {
  it('passes an empty conforming registry with a fresh aggregate', () => {
    const root = fixtureRoot()
    writeRegistry(root, [])
    writeAggregate(root, renderAggregate([]))
    expect(checkRegistry(root)).toEqual([])
  })

  it('reports a missing registry file and skips the meaningless aggregate check', () => {
    const root = fixtureRoot()
    const violations = checkRegistry(root)
    expect(violations).toHaveLength(1)
    expect(violations[0]?.path).toBe(REGISTRY_PATH)
    expect(violations[0]?.message).toContain('does not exist')
  })

  it('reports a stale aggregate', () => {
    const root = fixtureRoot()
    writeRegistry(root, [])
    writeAggregate(root, 'plugins: [something-else]\n')
    const violations = checkRegistry(root)
    expect(violations).toHaveLength(1)
    expect(violations[0]?.path).toBe(AGGREGATE_PATH)
    expect(violations[0]?.message).toContain('aggregate is stale')
  })

  it('keeps freshness out of the membership check so the write path can repair it', () => {
    const root = fixtureRoot()
    scaffoldPlugin(root, 'demo-clock', 'host')
    writeRegistry(root, ['demo-clock'])
    writeAggregate(root, 'stale\n')
    expect(checkRegistryMembership(root)).toEqual([])
    expect(checkRegistry(root)).toHaveLength(1)
  })

  it('reports unknown registrations and unregistered plugins in both directions', () => {
    const root = fixtureRoot()
    writeRegistry(root, ['ghost', 'demo-clock'])
    scaffoldPlugin(root, 'demo-clock', 'host')
    scaffoldPlugin(root, 'unlisted', 'host')
    writeAggregate(root, renderAggregate(['ghost', 'demo-clock']))
    const violations = checkRegistry(root)
    expect(violations).toHaveLength(2)
    expect(violations[0]?.path).toBe(REGISTRY_PATH)
    expect(violations[0]?.message).toContain('registered plugin "ghost" has no manifest')
    expect(violations[1]?.path).toBe('packages/plugins/unlisted/package.json')
    expect(violations[1]?.message).toContain('plugin "unlisted" is not listed in')
  })

  it('accepts a scaffolded plugin once registered with a fresh aggregate', () => {
    const root = fixtureRoot()
    scaffoldPlugin(root, 'demo-clock', 'host')
    writeRegistry(root, ['demo-clock'])
    writeAggregate(root, renderAggregate(['demo-clock']))
    expect(checkRegistry(root)).toEqual([])
    expect(readRegistry(root)).toEqual({ plugins: ['demo-clock'] })
    expect(existsSync(join(root, 'packages/plugins/demo-clock/cordis.yml'))).toBe(true)
  })

  it('rejects a registry entry that is not a kebab-case name', () => {
    const root = fixtureRoot()
    writeRegistry(root, ['Bad_Name'])
    writeAggregate(root, renderAggregate([]))
    const violations = checkRegistry(root)
    expect(violations).toHaveLength(1)
    expect(violations[0]?.path).toBe(REGISTRY_PATH)
    expect(violations[0]?.message).toContain('kebab-case names')
  })

  it('renders an aggregate a reader can statically include', () => {
    const root = fixtureRoot()
    scaffoldPlugin(root, 'demo-clock', 'host')
    writeRegistry(root, ['demo-clock'])
    writeAggregate(root, renderAggregate(['demo-clock']))
    const committed = readFileSync(join(root, AGGREGATE_PATH), 'utf8')
    expect(committed).toContain("name: '@deepseek-ai/cordis-plugin-include'")
    expect(committed).toContain('path: ./demo-clock/cordis.yml')
  })
})
