/**
 * Assemble the plugin registry aggregate: the committed
 * `packages/plugins/registry.json` membership list renders
 * `packages/plugins/aggregate.cordis.yml`, an include chain over each
 * registered plugin's own cordis.yml fragment. Default invocation writes the
 * aggregate; `--check` verifies membership both ways and the committed
 * aggregate's freshness without writing. Part of `hygiene`.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import {
  discoverPluginRecords,
  PLUGIN_GROUP,
  PLUGIN_NAME_PATTERN,
} from './plugin-manifests.ts'

const root = resolve(import.meta.dirname, '..')

export const REGISTRY_PATH = `${PLUGIN_GROUP}/registry.json`
export const AGGREGATE_PATH = `${PLUGIN_GROUP}/aggregate.cordis.yml`

/** Committed registry membership: the closed inventory of plugin names. */
export interface RegistryContents {
  plugins: string[]
}

/** One registry problem, addressed by repository-relative path. */
export interface RegistryViolation {
  path: string
  message: string
}

/** Registry entries are kebab-case plugin names. */
function isPluginNameArray(value: unknown): value is string[] {
  return Array.isArray(value)
    && value.every(name => typeof name === 'string' && PLUGIN_NAME_PATTERN.test(name))
}

/**
 * Parse and shape-check the committed registry file.
 * @param repoRoot - repository root.
 * @returns the validated membership list.
 * @throws when the file is missing, unparsable, or not `{ plugins: string[] }`.
 */
export function readRegistry(repoRoot: string): RegistryContents {
  const path = join(repoRoot, REGISTRY_PATH)
  if (!existsSync(path)) {
    throw new Error(`${REGISTRY_PATH} does not exist — create it with { "plugins": [] }`)
  }
  let parsed: unknown
  try {
    parsed = JSON.parse(readFileSync(path, 'utf8'))
  } catch (error) {
    throw new Error(
      `${REGISTRY_PATH} is not valid JSON: ${error instanceof Error ? error.message : String(error)}`,
    )
  }
  const plugins = (parsed as { plugins?: unknown }).plugins
  if (!isPluginNameArray(plugins)) {
    throw new Error(`${REGISTRY_PATH} must hold { "plugins": string[] } of kebab-case names`)
  }
  return { plugins }
}

/**
 * Render the aggregate include chain in registry order. An empty registry
 * renders an empty plugin list so the file stays a valid cordis overlay.
 * @param plugins - registered plugin names.
 * @returns the aggregate cordis.yml text.
 */
export function renderAggregate(plugins: readonly string[]): string {
  const lines = [
    '# Generated by scripts/assemble-registry.ts — do not edit by hand.',
    '# Regenerate: pnpm run plugin:assemble — verify: pnpm run plugin:assemble:check',
  ]
  if (plugins.length === 0) {
    lines.push('plugins: []')
  } else {
    lines.push('plugins:')
    for (const name of plugins) {
      lines.push(
        "  - name: '@deepseek-ai/cordis-plugin-include'",
        '    config:',
        `      path: ./${name}/cordis.yml`,
      )
    }
  }
  return `${lines.join('\n')}\n`
}

/**
 * Check the registry against discovery in both directions and compare the
 * committed aggregate with its rendering.
 * @param repoRoot - repository root.
 * @returns membership and freshness violations; empty when the registry conforms.
 */
export function checkRegistry(repoRoot: string): RegistryViolation[] {
  let registry: RegistryContents
  try {
    registry = readRegistry(repoRoot)
  } catch (error) {
    return [{
      path: REGISTRY_PATH,
      message: error instanceof Error ? error.message : String(error),
    }]
  }
  const { records } = discoverPluginRecords(repoRoot)
  const discovered = new Map(records.map(record => [
    typeof record.manifest.name === 'string' ? record.manifest.name : '',
    record.dir,
  ]))
  const violations: RegistryViolation[] = []
  for (const name of registry.plugins) {
    if (!discovered.has(name)) {
      violations.push({
        path: REGISTRY_PATH,
        message: `registered plugin "${name}" has no manifest at packages/plugins/${name}`,
      })
    }
  }
  for (const [name, dir] of discovered) {
    if (name === '') continue
    if (!registry.plugins.includes(name)) {
      violations.push({
        path: `${dir}/package.json`,
        message: `plugin "${name}" is not listed in ${REGISTRY_PATH} (the registry is a closed inventory)`,
      })
    }
  }
  const aggregatePath = join(repoRoot, AGGREGATE_PATH)
  if (!existsSync(aggregatePath)) {
    violations.push({
      path: AGGREGATE_PATH,
      message: 'aggregate file does not exist — run pnpm run plugin:assemble',
    })
  } else {
    const committed = readFileSync(aggregatePath, 'utf8')
    if (committed !== renderAggregate(registry.plugins)) {
      violations.push({
        path: AGGREGATE_PATH,
        message: 'aggregate is stale — run pnpm run plugin:assemble',
      })
    }
  }
  return violations
}

function formatRegistryViolations(violations: readonly RegistryViolation[]): string {
  return violations.map(violation => `  ${violation.path}: ${violation.message}`).join('\n')
}

const invokedPath = process.argv[1]
const isMain = invokedPath !== undefined
  && import.meta.url === pathToFileURL(resolve(invokedPath)).href
if (isMain) {
  const check = process.argv.includes('--check')
  const violations = checkRegistry(root)
  if (violations.length > 0) {
    console.error(`assemble-registry: violations found:\n${formatRegistryViolations(violations)}`)
    process.exit(1)
  }
  if (check) {
    console.log(`assemble-registry: ${readRegistry(root).plugins.length} registered plugin(s), aggregate fresh.`)
  } else {
    writeFileSync(join(root, AGGREGATE_PATH), renderAggregate(readRegistry(root).plugins))
    console.log(`assemble-registry: wrote ${AGGREGATE_PATH} (${readRegistry(root).plugins.length} plugin(s)).`)
  }
}
